# Generated by Django 2.0.13 on 2020-01-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
